// solid/src/App.jsx
import styles from './App.module.css'
import { createSignal, createEffect } from "solid-js"

function App() {
  const [blockchainData, setBlockchainData] = createSignal()
  const [triggerFetch, setTriggerFetch] = createSignal(false)
  const [isLoading, setIsLoading] = createSignal(false)

  const SERVER_URL = "http://localhost:3001/name/ajcwebdevtest"

  const fetchData = () => {
    setIsLoading(true)
    fetch(SERVER_URL)
      .then((response) => response.json())
      .then((data) => {
        setBlockchainData(data)
        setIsLoading(false)
      })
  }

  createEffect(() => {
    if (triggerFetch()) {
      fetchData()
      setTriggerFetch(false)
    }
  })

  return (
    <>
    <div class={styles.App}>
      <header class={styles.header}>
      <h1>Dash + Solid + Express</h1>
      <button onClick={() => setTriggerFetch(true)}>
        Fetch Data
      </button>
        {isLoading()
          ? "Loading..."
          : JSON.stringify(blockchainData(), null, 2)
        }
      </header>
    </div>
    </>
  )
}

export default App

// preact/src/app.jsx
import { useEffect, useState } from 'preact/hooks'
import './index.css'

export function App() {
  const [blockchainData, setBlockchainData] = useState()
  const [triggerFetch, setTriggerFetch] = useState(false)
  const [isLoading, setIsLoading] = useState(false)

  const fetchData = () => {
    setIsLoading(true)
    fetch('http://localhost:3001/name/ajcwebdevtest')
      .then(response => response.json())
      .then(data => {
        setBlockchainData(data)
        setIsLoading(false)
      })
  }

  useEffect(() => {
    if (triggerFetch) {
      fetchData()
      setTriggerFetch(false)
    }
  }, [triggerFetch])

  return (
    <div>
      <h1>Dash + Preact + Express</h1>
      <button onClick={() => setTriggerFetch(true)}>
        Fetch Data
      </button>
      <p class="leftCenter">
        <pre class="preLeft">
          {isLoading
            ? 'Loading...'
            : JSON.stringify(blockchainData, null, 2)
          }
        </pre>
      </p>
    </div>
  )
}
